### PR TITLE
Free the memory! Start by understanding 'freedom' as a whole.

### PR DESCRIPTION
**Pull request by ElJaviLuki**
I understand your omission in freeing up memory; after all, in an environment that favors submission and favoritism over genuine passion, the notion of freedom seems to be a foreign concept

### CODE REVIEW

**Comment by shernandiu** [comment]
Claro, libera memoria tras un bucle infinito. Muy útil. 🚬🌿

**Comment by ElJaviLuki** [comment]
Buena suerte a quien trate de encontrar una fuga de memoria en un sistema escalable que dependa de esto crack

**Comment by shernandiu** [comment]
vale

**Comment by ElJaviLuki** [comment]
No es nada personal amigo. Más bien la crítica va al sistema que te da cancha

**Pull request closed without merging**
